modLoader="javafml" #mandatory
loaderVersion="[31,)"
[[mods]]
modId="keybindingmod"
version="${file.jarVersion}"
displayName="Keybinding Mod"
authors="Stefan"
description='''
Keybinding Mod für 1.15.2 Minecraft
'''
[[dependencies.keybindingmod]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.keybindingmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="CLIENT"
